version: "3"

services:
  database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "filescanner"
      POSTGRES_PASSWORD: "secure_password"
      POSTGRES_DB: "scanner"

  filescanner:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - /home/mg/Downloads:/data
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/scanner
      - scanner.folder.path=/data

